
    create table adult_user (
        id bigint generated by default as identity,
        user_id bigint unique,
        wallet_id bigint unique,
        cpf varchar(255) not null unique,
        email varchar(255) not null unique,
        job varchar(255),
        primary key (id)
    );

    create table adult_user_dependents (
        adult_user_id bigint not null,
        dependents_id bigint not null unique
    );

    create table adult_user_tasks (
        adult_user_id bigint not null,
        tasks_id bigint not null unique
    );

    create table child_task (
        status tinyint not null check (status between 0 and 3),
        value float(53) not null,
        adult_user_id bigint,
        child_user_id bigint,
        id bigint generated by default as identity,
        description varchar(255) not null,
        primary key (id)
    );

    create table child_user (
        family tinyint check (family between 0 and 3),
        birthday timestamp(6) not null,
        guardian_id bigint,
        id bigint generated by default as identity,
        user_id bigint unique,
        wallet_id bigint unique,
        primary key (id)
    );

    create table child_user_objectives (
        child_user_id bigint not null,
        objectives_id bigint not null unique
    );

    create table child_user_tasks (
        child_user_id bigint not null,
        tasks_id bigint not null unique
    );

    create table objective (
        current_amount float(53) not null,
        objective_value float(53) not null,
        child_user_id bigint,
        id bigint generated by default as identity,
        description varchar(255) not null,
        primary key (id)
    );

    create table release (
        type tinyint not null check (type between 0 and 1),
        value float(53) not null,
        date timestamp(6) not null,
        id bigint generated by default as identity,
        wallet_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table user (
        id bigint generated by default as identity,
        name varchar(255) not null,
        nickname varchar(255) not null,
        password varchar(255) not null,
        primary key (id)
    );

    create table wallet (
        money float(53) not null,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table wallet_extract (
        extract_id bigint not null unique,
        wallet_id bigint not null
    );

    alter table if exists adult_user 
       add constraint FKsxflfdtyk0t9lg9qhgl9b1wvo 
       foreign key (user_id) 
       references user;

    alter table if exists adult_user 
       add constraint FKnt1cxkxka5p4ay00f9bta1r49 
       foreign key (wallet_id) 
       references wallet;

    alter table if exists adult_user_dependents 
       add constraint FK6ta03vh4brewvmuu03rjr71j1 
       foreign key (dependents_id) 
       references child_user;

    alter table if exists adult_user_dependents 
       add constraint FKq83j5lvx0gopsstcaoopqrlcc 
       foreign key (adult_user_id) 
       references adult_user;

    alter table if exists adult_user_tasks 
       add constraint FK2gy86m2xxjeasjul64csw57bw 
       foreign key (tasks_id) 
       references child_task;

    alter table if exists adult_user_tasks 
       add constraint FKr3bvmgknfveqv6usc8hgt11uu 
       foreign key (adult_user_id) 
       references adult_user;

    alter table if exists child_task 
       add constraint FKn45wewbxg8wlpwqih471v87fu 
       foreign key (adult_user_id) 
       references adult_user;

    alter table if exists child_task 
       add constraint FKi9a1as0w51ip2ahcdlmrf3wnd 
       foreign key (child_user_id) 
       references child_user;

    alter table if exists child_user 
       add constraint FKnulfcpkkk11d7evcvfk7t977o 
       foreign key (guardian_id) 
       references adult_user;

    alter table if exists child_user 
       add constraint FKaj56y39w10rl5wo9ibsjvn9b8 
       foreign key (user_id) 
       references user;

    alter table if exists child_user 
       add constraint FKe7tsl4jqnbim8unyp1amrd3t3 
       foreign key (wallet_id) 
       references wallet;

    alter table if exists child_user_objectives 
       add constraint FKoipyck3x35qw278su78vhp95v 
       foreign key (objectives_id) 
       references objective;

    alter table if exists child_user_objectives 
       add constraint FKqkyhho1eyv97r5oequ6mv2gdq 
       foreign key (child_user_id) 
       references child_user;

    alter table if exists child_user_tasks 
       add constraint FKbsmxllmfa29j8j8t9pccelxi5 
       foreign key (tasks_id) 
       references child_task;

    alter table if exists child_user_tasks 
       add constraint FKpinxre9b2sgfqe0xh7kucvger 
       foreign key (child_user_id) 
       references child_user;

    alter table if exists objective 
       add constraint FKrqyba89ln58vyxshix55h863x 
       foreign key (child_user_id) 
       references child_user;

    alter table if exists release 
       add constraint FKsts4i7fe65ys3bu0ilfsk05f9 
       foreign key (wallet_id) 
       references wallet;

    alter table if exists wallet_extract 
       add constraint FKm55tjauluq06w9g0pygp7x0nu 
       foreign key (extract_id) 
       references release;

    alter table if exists wallet_extract 
       add constraint FK3lk175xwm50abcbvg9a8qwbuf 
       foreign key (wallet_id) 
       references wallet;
