name: Deploy Produção

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: poupi
  IMAGE_VERSION: latest
  CONTAINER_NAME: poupi

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Adiciona credenciais de banco de dados
        env:
          DBCREDENTIALS: ${{ secrets.DBCREDENTIALS }}
        run: echo $DBCREDENTIALS > ./codebusters/src/main/resources/application-test.properties

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./codebusters
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}